name: SeamlessLinks
author: DroppingAnvil
description: An overdone Discord/Voting/Webiste/Anything link system by Dropping Anvil
main: com.seamlessfactions.seamlesslinks.SeamlessLinks
version: 2.0 BETA